//
// Generated file, do not edit! Created by opp_msgtool 6.3 from NetworkPacket.msg.
//

#ifndef __NETWORKPACKET_M_H
#define __NETWORKPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class NetworkPacket;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

// cplusplus {{
#include "inet/common/packet/chunk/FieldsChunk.h"
// }}

/**
 * Enum generated from <tt>NetworkPacket.msg:9</tt> by opp_msgtool.
 * <pre>
 * enum WsnPacketType
 * {
 *     DATA = 0;
 *     HELLO = 1;
 *     CH_ADV = 2;
 *     JOIN_REQ = 3;
 *     TDMA_SCH = 4;
 * }
 * </pre>
 */
enum WsnPacketType {
    DATA = 0,
    HELLO = 1,
    CH_ADV = 2,
    JOIN_REQ = 3,
    TDMA_SCH = 4
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WsnPacketType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WsnPacketType& e) { int n; b->unpack(n); e = static_cast<WsnPacketType>(n); }

/**
 * Class generated from <tt>NetworkPacket.msg:18</tt> by opp_msgtool.
 * <pre>
 * // Inherit from inet::FieldsChunk so it works with the Radio
 * class NetworkPacket extends inet::FieldsChunk
 * {
 *     int srcId;
 *     int destId;      // -1 for Broadcast
 *     int type \@enum(WsnPacketType);
 *     int sequenceNumber;
 *     double residualEnergy;
 *     double xPos;
 *     double yPos;
 * }
 * </pre>
 */
class NetworkPacket : public ::inet::FieldsChunk
{
  protected:
    int srcId = 0;
    int destId = 0;
    int type = 0;
    int sequenceNumber = 0;
    double residualEnergy = 0;
    double xPos = 0;
    double yPos = 0;

  private:
    void copy(const NetworkPacket& other);

  protected:
    bool operator==(const NetworkPacket&) = delete;

  public:
    NetworkPacket();
    NetworkPacket(const NetworkPacket& other);
    virtual ~NetworkPacket();
    NetworkPacket& operator=(const NetworkPacket& other);
    virtual NetworkPacket *dup() const override {return new NetworkPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual int getDestId() const;
    virtual void setDestId(int destId);

    virtual int getType() const;
    virtual void setType(int type);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);

    virtual double getResidualEnergy() const;
    virtual void setResidualEnergy(double residualEnergy);

    virtual double getXPos() const;
    virtual void setXPos(double xPos);

    virtual double getYPos() const;
    virtual void setYPos(double yPos);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NetworkPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NetworkPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline NetworkPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<NetworkPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __NETWORKPACKET_M_H

